### ISSUE TITLE
Apply ggtangle for enrichResults objects

### ISSUE THREAD

**Issue by yeroslaviz** [YuLab-SMU/ggtangle#1]
Hi, thanks for the great addition to the ggplot2 world.

As was asked [here](https://github.com/YuLab-SMU/enrichplot/issues/293#issuecomment-2460767902), I would like to adapt my `cnetplot` from the ClusterProfiler results to remove some of my nodes.

But the ggtangle::cnetplot can't accept such an object (or a data.frame for that matter).

What are the alternatives?

thanks

Assa

**Comment by GuangchuangYu** [comment]
`enrichplot::cnetplot()` should work.

**Comment by GuangchuangYu** [comment]
don't open a new issue if it is a follow-up.
